Feature/automation structure
ZupIT/beagle-web-components pull request #11
Opened 2020-09-29 20:49 UTC by pedronaveszup

2020-10-02 19:47 UTC, Tiagoperes requested changes

2020-10-02 19:47 UTC, Tiagoperes commented on automatedTests/angular/src/app/app.component.html
> +<beagle-remote-view [loadParams]="loadParams"></beagle-remote-view>
Esse uso foi depreciado. Vai funcionar, mas terão warnings no console.

A partir da 1.3, o uso correto é:

```html
<beagle-remote-view [route]="route"></beagle-remote-view> 
```

No seu controller:

```typescript
route: string

// ...
 
constructor() {
  this.route = this.queryParams.get('path') || '/payload.json'
}
```

2020-10-02 19:47 UTC, Tiagoperes commented on automatedTests/react/public/payload.json
> +{
Vc não pretende replicar os exemplos em cada projeto não né?

2020-10-02 19:47 UTC, Tiagoperes commented on automatedTests/react/src/App.tsx
> +      <BeagleRemoteView path={path} />
depreciado. Vai funcionar, mas com warnings. Basta renomear "path" para "route".

2020-10-07 19:25 UTC, Tiagoperes submitted a review, later dismissed

2020-10-14 19:06 UTC, Tiagoperes approved these changes

2020-10-14 19:44 UTC, carolinegoncalveszup approved these changes

2020-10-14 19:47 UTC, merged