add sendRequest test
ZupIT/beagle-web-components pull request #26
Opened 2020-10-21 13:34 UTC by jamessonpenhazup

What I did
I created the tests for the sendRequest.

How I did it
I created the tests for the sendRequest using cypress and cucumber.

How to verify it
yarn test:angular:9 TAGS="@sendrequest"

Description for the changelog
Tests for the sendrequest.

2020-10-21 13:39 UTC, tayronemachadozup approved these changes

2020-10-23 19:18 UTC, Tiagoperes requested changes
Eu fiz alguns comentários que vão servir para os seus próximos testes. Mas, mesmo corrigindo todos eles, os testes continuarão errados. Isso vai acontecer pq a ideia do teste em si não está certa. Vou explicar nesse comentário geral, como esse teste de alerta deveria ser feito.

O alerta é uma função de sistema e não um componente. Se vc analisar o HTML, por exemplo, o alerta nunca cria um elemento novo. Dessa forma, é impossível vc selecionar o alerta via `cy.get` ou qualquer coisa do tipo.

Para esses eventos de sistema, o cypress oferece a função `cy.on` que observa quando algum evento acontecer. Para o alerta, podemos usar `cy.on('window:alert', callback)`. O callback recebe a mensagem passada para o alerta.

Como precisamos estar observando o alert quando ele ocorre. Não adianta fazermos um teste do tipo "clique no botão e então comece a observar os alertas". O que devemos fazer é começar a observar os alertas ANTES de clicar no botão. Na verdade, o mais correto, é começar a observar os alertas assim que a página é carregada.

Dessa forma, o teste deve ser executado na seguinte ordem:
1. Carregue a página
2. Quando a página estiver carregada, comece a observar os alertas
3. Clique no botão
4. Verifique se o alerta apareceu.

Mas, como verificar se o alerta apareceu? Basta a gente gravar a mensagem do alerta em uma variável, veja:

```typescript
class SendRequestPage extends BeaglePage {
  private lastAlertMessage = ''
  // ...
  cy.on('window:alert', message => this.lastAlertMessage = message)
  // ...
}
```

Dessa forma, sempre que acontece um alerta, a mensagem é gravada em `this.lastAlertMessage`. Assim, no passo 4, podemos fazer:

```typescript
expect(this.lastAlertMessage).to.equal(expectedMessage)
```

O problema que fica faltando resolver é: como começar a observar os alertas assim que a página carregar?

Para fazer isso, a maioria das funções do cypress tem um método `.then()` que garante que a função passada só vai executar quando a anterior tiver terminado. Nós carregamos a página na função `init()` da classe `BeagleView`. O primeiro passo é alterar essa função para que ela retorne o `cy` que ela está usando para que possamos fazer um `.then` nele.

```typescript
class BeaglePage {
  private path: string
  
  constructor(path: string) {
    this.path = path
  }

  init() {
    return cy.visit(`${url}?path=${this.path}`)
  }
}
```

Note que eu adicionei um `return`.

Agora, na classe `SendRequestPage`, precisamos sobrescrever o `init()`:

```typescript
init() {
    return super.init().then(() => {
      cy.on('window:alert', message => this.lastAlertMessage = message)
    })
  }
```

Pronto! Assim garantimos que logo depois de inicializar a página do sendRequest, estaremos observando o alerta e sempre que um alerta é chamado, o valor de `this.lastAlertMessage` será trocado pelo texto da mensagem.

O código completo da classe `SendRequestPage` ficaria:

```typescript
class SendRequestPage extends BeaglePage {
  lastAlertMessage = ''

  constructor() {
    super('send-request')
  }

  init() {
    return super.init().then(() => {
      cy.on('window:alert', message => this.lastAlertMessage = message)
    })
  }

  clickButton(text: string) {
    SendRequestElements.buttonWithText(text).click()
  }

  checkAlert(message: String){
    expect(this.lastAlertMessage).to.equal(message)
  }
  
  checkButton(){
    SendRequestElements.buttonWithText('didFinish').should('exist')
  }
}
```

2020-10-27 15:30 UTC, Tiagoperes approved these changes

2020-11-06 13:00 UTC, hectorcustodiozup approved these changes

2020-11-25 17:32 UTC, merged