Feature/input tests
ZupIT/beagle-web-components pull request #30
Opened 2020-10-29 20:02 UTC by tayronemachadozup

- What I did
I created the tests for the input Text.

- How I did it
I created the tests for the  input Text using cypress and cucumber.

- How to verify it
Running yarn test:angular:9 TAGS="@textInput" or yarn cypress:open 

- Branch:
The bbf for this test is in the textoreputTests branch of the monorepo: https://github.com/ZupIT/beagle/tree/textinputTests

2020-10-30 12:47 UTC, jamessonpenhazup submitted a review, later dismissed

2020-10-30 14:31 UTC, Tiagoperes requested changes
Tip: fix the problems in the `.feature` file first.

2020-10-30 14:31 UTC, Tiagoperes commented on automated-tests/common/cypress/integration/TextInputScreen.feature
> +        Then I must check if the textInput value <textInputValue> appears on the screen
Why are the inputs sometimes referred by value and sometimes by placeholder (hint)? It would be better if we had a pattern.

2020-10-30 14:31 UTC, Tiagoperes commented on automated-tests/common/cypress/integration/TextInputScreen.feature
> +        When the placeholder <textInputDisabled> of the disabled field is on the screen
When should describe an action. This is not an action, what should be done here?

2020-10-30 14:31 UTC, Tiagoperes commented on automated-tests/common/cypress/integration/TextInputScreen.feature
> +        When the value <textInputReadOnly> of the readOnly field is on the screen
When should describe an action. This is not an action, what should be done here?

2020-10-30 14:31 UTC, Tiagoperes commented on automated-tests/common/cypress/support/steps/text-input-step.ts
> +/*
I won't review this file for now, since it's directly linked to the `.feature` file, which, in my opinion, needs some work.

2020-11-25 17:36 UTC, Tiagoperes submitted a review, later dismissed

2020-11-25 18:18 UTC, Tiagoperes approved these changes

2020-11-25 18:18 UTC, jamessonpenhazup approved these changes

2020-11-25 18:19 UTC, merged