add addChildren test
ZupIT/beagle-web-components pull request #31
Opened 2020-10-29 21:07 UTC by jamessonpenhazup

What I did
I created the tests for the AddChildren.

How I did it
I created the tests for the AddChildren using cypress and cucumber.

How to verify it
yarn test:angular:9 TAGS="@addChildren"
Branch: master
Beagle version: 1.4.0

Description for the changelog
Tests for the AddChildren.

2020-10-30 15:00 UTC, Tiagoperes requested changes
Although there are many comments, they're just observations. The only thing I ask is for you to change the names of the two methods I commented in you page file.

2020-11-25 17:37 UTC, Tiagoperes approved these changes

2020-11-25 17:41 UTC, tayronemachadozup approved these changes

2020-11-25 18:12 UTC, tayronemachadozup approved these changes

2020-11-25 18:13 UTC, merged