Feature/analytics2.0
ZupIT/beagle-web-components pull request #46
Opened 2020-12-30 20:32 UTC by tayronemachadozup

- What I did
I created the tests for the analytics 2.0.

- How I did it
I created the tests for the analytics 2.0 using cypress and cucumber.

- How to verify it
Running yarn test:angular:9 TAGS="@analytics2.0" or yarn cypress:open 

- Branch:
The bff of these test are in the feature/analytics2.0Testes of the monorepo

2021-03-09 12:23 UTC, Tiagoperes requested changes

2021-03-09 12:23 UTC, Tiagoperes commented on automated-tests/angular9/package.json
> +    "@zup-it/beagle-angular": "^1.5.0",
1.6.0

2021-03-09 12:23 UTC, Tiagoperes commented on automated-tests/angular9/package.json
> +    "@zup-it/beagle-web": "^1.5.0",
this dependency should not be needed

2021-03-24 18:23 UTC, arthurbleilzup requested changes

2021-03-24 18:23 UTC, arthurbleilzup commented on automated-tests/angular9/src/app/beagle.component.ts
> +  title = 'beagle-automated-tests-angular';
You can remove this title, because it is not used anywhere

2021-03-24 18:23 UTC, arthurbleilzup commented on automated-tests/angular9/src/app/screen-analytics-link.component.ts
> +  title = 'beagle-automated-tests-angular';
You can remove title because it is not used anywhere

2021-04-08 14:41 UTC, arthurbleilzup approved these changes

2021-05-03 12:45 UTC, igorgiumellizup approved these changes

2021-06-10 12:10 UTC, Tiagoperes approved these changes

2021-06-10 12:10 UTC, merged