Fixed broken tests of angular 9 (WEB)
ZupIT/beagle-web-components pull request #52
Opened 2021-03-22 14:28 UTC by tayronemachadozup

Este pr corrige os seguintes testes:

ButtonScreen.feature
SendRequestScreen.feature
SimpleFormScreen.feature
TextInputScreen.feature
ConfirmScreen.feature

Closes: #50

2021-03-24 18:05 UTC, arthurbleilzup requested changes

2021-03-24 18:05 UTC, arthurbleilzup commented on automated-tests/common/tsconfig.json
> +    "types": ["cypress","@types/node"]
```suggestion
    "types": ["cypress", "node"]
```

2021-03-24 18:05 UTC, arthurbleilzup commented on automated-tests/common/cypress/support/page-objects/ConfirmPage.ts
> +            cy.wait(1000)
Why should you wait?

2021-03-24 20:45 UTC, tayronemachadozup commented on automated-tests/common/cypress/support/page-objects/ConfirmPage.ts
> +            cy.wait(1000)
I checked and it really is unnecessary. Thank you!

2021-03-25 18:45 UTC, arthurbleilzup approved these changes

2021-04-06 19:05 UTC, arthurbleilzup submitted a review, later dismissed

2021-04-12 14:47 UTC, arthurbleilzup approved these changes

2021-05-03 12:46 UTC, igorgiumellizup approved these changes

2021-05-03 12:46 UTC, igorgiumellizup commented on automated-tests/common/cypress/integration/TouchableScreen.feature
> +
Too much spaces here

2021-05-04 19:08 UTC, igorgiumellizup approved these changes

2021-05-04 19:09 UTC, arthurbleilzup approved these changes

2021-05-04 20:25 UTC, Tiagoperes approved these changes

2021-05-04 20:27 UTC, merged